import type { Metadata } from "next";
import "./globals.css";
import MainLayout from "@/lib/layouts/MainLayout";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { getServerSession } from "next-auth";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "ECT Chatbot",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Preload session on the server to avoid client flicker
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body>
        <MainLayout session={session}>
          {children}
        </MainLayout>
      </body>
    </html>
  );
}
